Repository cfsengineering/CEASIOMpy, pull requests merged in 2023-02, with the labels that each got.

#273 Add testcase 4
  README.md
  src/bin/ceasiompy_exec.py
  test_cases/test_case_4/README.md
Labels: documentation

#274 Add test case 5
  README.md
  src/bin/ceasiompy_exec.py
  test_cases/test_case_5/README.md
Labels: documentation

#275 Fix software logos
  ceasiompy/CPACS2GMSH/README.md
  ceasiompy/PyTornado/README.md
  ceasiompy/SU2Run/README.md
Labels: documentation, fix

#276 Improve `su2automesh` code
  ceasiompy/SUMOAutoMesh/sumoautomesh.py
Labels: Python

#278 cfl adaptation and param values
  ceasiompy/SU2Run/__specs__.py
  ceasiompy/SU2Run/func/su2config.py
  ceasiompy/utils/commonxpath.py
Labels: SU2
